//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Master
    {
        public string Activity_Code { get; set; }
        public string Activity_Description { get; set; }
        public string Activity_Group { get; set; }
        public string Activity_Document { get; set; }
        public string Activity_Type { get; set; }
        public string Activity_Predessor { get; set; }
        public string Activity_Exe_Time { get; set; }
        public string CompID { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_on { get; set; }
        public int id { get; set; }
    }
}
