//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Child
    {
        public int id { get; set; }
        public string Activity_Code { get; set; }
        public string Activity_Res_Id { get; set; }
        public string Act_Res_Skill_Level { get; set; }
        public string Act_Noof_Res { get; set; }
        public string Act_Res_Cost { get; set; }
        public string CompID { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Modified_On { get; set; }
        public Nullable<System.DateTime> Modified_By { get; set; }
    }
}
