//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Thermal_PMSEntities : DbContext
    {
        public Thermal_PMSEntities()
            : base("name=Thermal_PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity_Child> Activity_Child { get; set; }
        public virtual DbSet<Activity_Master> Activity_Master { get; set; }
        public virtual DbSet<APG_Master> APG_Master { get; set; }
        public virtual DbSet<Customer_Master> Customer_Master { get; set; }
        public virtual DbSet<Group_Master> Group_Master { get; set; }
        public virtual DbSet<Item_RM_Codes> Item_RM_Codes { get; set; }
        public virtual DbSet<Item_RM_Master> Item_RM_Master { get; set; }
        public virtual DbSet<Maker_Master> Maker_Master { get; set; }
        public virtual DbSet<Material_Grades> Material_Grades { get; set; }
        public virtual DbSet<Part_List> Part_List { get; set; }
        public virtual DbSet<Part_List_Item> Part_List_Item { get; set; }
        public virtual DbSet<Project_ActivityChart> Project_ActivityChart { get; set; }
        public virtual DbSet<Project_Commercial_Data> Project_Commercial_Data { get; set; }
        public virtual DbSet<Project_Master> Project_Master { get; set; }
        public virtual DbSet<Project_Master_Child> Project_Master_Child { get; set; }
        public virtual DbSet<Project_Structure> Project_Structure { get; set; }
        public virtual DbSet<Project_Structure_Main> Project_Structure_Main { get; set; }
        public virtual DbSet<Project_Technical_Data> Project_Technical_Data { get; set; }
        public virtual DbSet<Project_Technical_Data_Child> Project_Technical_Data_Child { get; set; }
        public virtual DbSet<Project_Version_History> Project_Version_History { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SubAssembly_Master> SubAssembly_Master { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Temptable> Temptables { get; set; }
        public virtual DbSet<UOM_Master> UOM_Master { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Login> User_Login { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<Variant_Master> Variant_Master { get; set; }
        public virtual DbSet<WorkCenter> WorkCenters { get; set; }
    }
}
