//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_Master
    {
        public int Id { get; set; }
        public string Group_Id { get; set; }
        public string Group_Name { get; set; }
        public string CompID { get; set; }
        public string Created { get; set; }
        public Nullable<System.DateTime> Created_By { get; set; }
        public string Modified { get; set; }
        public Nullable<System.DateTime> Modified_By { get; set; }
    }
}
