//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_RM_Codes
    {
        public string Item_Spec { get; set; }
        public Nullable<decimal> Item_Dia { get; set; }
        public Nullable<decimal> Item_WT { get; set; }
        public string Item_SchNo { get; set; }
        public Nullable<decimal> Item_UWt { get; set; }
        public string Item_Description { get; set; }
        public string Item_Code { get; set; }
        public string Item_LongText { get; set; }
        public string CompID { get; set; }
        public int id { get; set; }
        public string Part_List_No { get; set; }
    }
}
