//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_RM_Master
    {
        public string Item_Type { get; set; }
        public string Item_Group { get; set; }
        public string Item_Pur_UOM { get; set; }
        public string Item_Iss_UOM { get; set; }
        public string Item_Spec { get; set; }
        public string Item_PTS { get; set; }
        public string Item_BOM_Req { get; set; }
        public string Item_Critical_Item { get; set; }
        public string Item_ShelfLife { get; set; }
        public string CompID { get; set; }
        public int id { get; set; }
    }
}
