//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part_List_Item
    {
        public int id { get; set; }
        public string Project_Code { get; set; }
        public string Maker_No { get; set; }
        public string Apg_No { get; set; }
        public string Apg_Name { get; set; }
        public string Partlist_No { get; set; }
        public string Part_Group { get; set; }
        public string Part_Sl_No { get; set; }
        public string Part_Name { get; set; }
        public string Part_Desription { get; set; }
        public string Part_variant { get; set; }
        public string Part_UOM { get; set; }
        public string Part_Spec_Id { get; set; }
        public string Part_Rm_Type { get; set; }
        public Nullable<decimal> Part_Rm_WThick { get; set; }
        public Nullable<decimal> Part_Rm_Density { get; set; }
        public string Part_Mtc_Cert { get; set; }
        public string Part_IBR_Cert { get; set; }
        public string Part_EN_Cert { get; set; }
        public string Part_RM_Code { get; set; }
        public Nullable<decimal> Part_Dia { get; set; }
        public Nullable<decimal> Part_Wt { get; set; }
        public Nullable<decimal> Part_Length { get; set; }
        public Nullable<decimal> Part_W2 { get; set; }
        public Nullable<decimal> Part_Fg_wt { get; set; }
        public Nullable<decimal> Part_Rm_Wt { get; set; }
        public Nullable<decimal> Part_D_Wt { get; set; }
        public string Part_Engg_Code { get; set; }
        public string CompId { get; set; }
        public string Version_No { get; set; }
        public Nullable<System.DateTime> Version_Date { get; set; }
        public string Version_Change { get; set; }
        public string Created { get; set; }
        public Nullable<System.DateTime> Creted_By { get; set; }
        public string Modified { get; set; }
        public Nullable<System.DateTime> Modified_By { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> OD { get; set; }
        public string Part_Equipment_Name { get; set; }
        public string Status { get; set; }
        public string Drawing_NO { get; set; }
        public string PTS_NO { get; set; }
        public string Main_Drwaing_No { get; set; }
    }
}
