//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Commercial_Data
    {
        public int id { get; set; }
        public string Project_Code { get; set; }
        public string Project_Clasificaton { get; set; }
        public string Project_Sector { get; set; }
        public string Project_Currency { get; set; }
        public string LDfor_Delyed_Deliveryfor_Equp { get; set; }
        public string LDfor_Delyed_Deliveryfor_Draw { get; set; }
        public string Mile_Stone { get; set; }
        public string Per_Payments { get; set; }
        public string TriggeringPoint { get; set; }
        public string CompID { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    }
}
