//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_ActivityChart
    {
        public int id { get; set; }
        public string Project_Code { get; set; }
        public string Activity_Code { get; set; }
        public string Activity_Description { get; set; }
        public string Work_Center { get; set; }
        public string Person_Rep { get; set; }
        public string Planned_StartDate { get; set; }
        public string Planned_CompletionDate { get; set; }
        public string Actual_StartDate { get; set; }
        public string Actual_Completiondate { get; set; }
        public string Status { get; set; }
        public string CompID { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Maker_No { get; set; }
        public string Partlist_No { get; set; }
        public string Apg_No { get; set; }
        public string Apg_Name { get; set; }
        public string Part_Engg_Code { get; set; }
    }
}
