//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Version_History
    {
        public int id { get; set; }
        public string Project_Code { get; set; }
        public string Version_No { get; set; }
        public Nullable<System.DateTime> Version_Date { get; set; }
        public string Version_Change { get; set; }
        public string DCN_No { get; set; }
        public string Created_By { get; set; }
        public string Reviewed_By { get; set; }
        public string Approved_By { get; set; }
        public string CompID { get; set; }
    }
}
