//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temptable
    {
        public int id { get; set; }
        public string Maker_No { get; set; }
        public string Created_By { get; set; }
        public string CompID { get; set; }
        public string Project_Code { get; set; }
        public Nullable<int> no { get; set; }
    }
}
