//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInRole
    {
        public int RoleId { get; set; }
        public string roleName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> createdbyid { get; set; }
        public string createdbyname { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
