//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPLoginpages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Login
    {
        public int LoginId { get; set; }
        public string username { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string userid { get; set; }
    }
}
